services:
  - type: web
    name: nbf-listados
    runtime: docker
    region: ohio
    plan: free
    branch: main

    # Variables de entorno
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DB_DRIVER
        value: "FreeTDS"
      - key: DB_PORT
        value: "1433"

    # Health check
    healthCheckPath: /

    # Logs
    buildCommand: |
      pip install -r requirements.txt && \
      flask db upgrade || true
